name: Docs

on:
  push:

jobs:
  docs:
    name: Lint ubuntu-latest Py3.10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        # This gets all branches (1 = only current branch)
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build documentation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash -l {0}
      run: |
        docs/buildDocs.sh
        
